FROM clojure:temurin-21-tools-deps-1.11.1.1429-jammy
# Ubuntu: Ubuntu 22.04 LTS (Jammy Jellyfish)
# JDK: eclipse-temurin 21
# Clojure: tools-deps, 1.11.1.1429

# Extra tools
RUN apt-get update && apt-get install -y gpg curl nodejs npm

RUN clojure -Ttools install-latest :lib io.github.seancorfield/deps-new :as new

# Add Babashka
RUN curl -sLO https://raw.githubusercontent.com/babashka/babashka/master/install \
  && chmod +x install \
  && ./install --static